/*
    This is for cma3 strategy. 
    Yearly better half of symbols based on 'cma3sell' strategy performance
*/

const Tagger = require('../types/Tagger'); 

const ALLOWED_SYMBOLS = [
    'LITUSDT','DENTUSDT','ANTUSDT','TRBUSDT','ENJUSDT','STMXUSDT','SRMUSDT','DASHUSDT','ANKRUSDT','ETCUSDT','ICXUSDT','XRPUSDT','XTZUSDT','SXPUSDT','AUDIOUSDT','QTUMUSDT','ALGOUSDT','STORJUSDT','XEMUSDT','BLZUSDT','LRCUSDT','REEFUSDT','BCHUSDT','RLCUSDT','1000XECUSDT','XMRUSDT','LPTUSDT','AKROUSDT','FILUSDT','ETHUSDT','GALAUSDT','FLMUSDT','BANDUSDT','HBARUSDT','NKNUSDT','DEFIUSDT','IOTAUSDT','MASKUSDT','IOSTUSDT','DOTUSDT','GRTUSDT','MATICUSDT','IOTXUSDT','BNBUSDT','SCUSDT','CELRUSDT','ARPAUSDT','EOSUSDT','ALPHAUSDT','SKLUSDT','DYDXUSDT','ONEUSDT','VETUSDT','SOLUSDT','BELUSDT','MTLUSDT','DUSKUSDT','1INCHUSDT','FTMUSDT','RENUSDT','ZILUSDT','ADAUSDT','BALUSDT','DODOUSDT','CELOUSDT','1000SHIBUSDT','WOOUSDT','JASMYUSDT','APEUSDT','BNXUSDT','FLOWUSDT','ANCUSDT','PEOPLEUSDT','ROSEUSDT','API3USDT','IMXUSDT'
];

class CUSTOM4 extends Tagger {

    getTags(order, flags, orders, tags) 
    {
        const key = order.symbol;
    
        return {
            CU4: { value:  ( ALLOWED_SYMBOLS.includes(key) ? 'Y' : 'N') },
        }

    }

}

module.exports = CUSTOM4;

